### ISSUE TITLE
Invalid arguments in hpe_nimble_group module

### ISSUE THREAD

**Issue by xenlo** [hpe-storage/nimble-ansible-modules#55]
## SUMMARY
The module `hpe_nimble_group` complains the following arguments:
- `smtp_server`: It is missing as argument in the module but exist in the REST API
- `alert_from_email_addr`: It expects `alert_from_email_addrs` (when it didn't has 's' in the REST API) But if we add an 's' the syntax is ok but I get a python error say that it cannot deal with `alert_from_email_addrs`.
- `alarms`: no clue yet because this one is well documented in the module doc.

## ISSUE TYPE
- Bug Report

## COMPONENT NAME
- hpe.nimble.hpe_nimble_group

## ANSIBLE VERSION
- ansible [core 2.11.12]

## COLLECTION VERSION
- hpe.nimble v1.1.4

## STEPS TO REPRODUCE
Simply run the following task on your nimble:
```
- name: Update group information
  hpe.nimble.hpe_nimble_group:
    host: "{{ nimble_mgmt_host }}"
    username: "{{ nimble_username }}"
    password: "{{ nimble_password }}"
    name: "{{ group_name }}"
    smtp_server: "{{ nimble_smtp_server }}"
    smtp_port: "{{ nimble_smtp_port }}"
    alert_from_email_addr: "{{ nimble_alert_from_email_addr }}"
    alert_to_email_addrs: "{{ nimble_alert_to_email_addrs | join(',') }}"
    alarms: true
    state: "present"
```
## EXPECTED RESULTS
It updates the smpt server, the source alert email, and the alarms accordingly

## ACTUAL RESULTS
```
TASK [ptc_san_nimble : Update group information] ****************************************************************************************
jeudi 06 octobre 2022  14:53:07 +0200 (0:00:00.321)       0:00:07.568 ********* 
fatal: [nimble -> localhost]: FAILED! => changed=false 
  msg: 'Group update failed | ''{''messages'': [{''code'': ''SM_http_bad_request'', ''severity'': ''error'', ''text'': ''The request could not be understood by the server.''}, {''code'': ''SM_unexpected_arg'', ''severity'': ''error'', ''arguments'': {''arg'': ''alarms''}, ''text'': "Unexpected argument ''alarms''."}, {''code'': ''SM_unexpected_arg'', ''severity'': ''error'', ''arguments'': {''arg'': ''alert_from_email_addrs''}, ''text'': "Unexpected argument ''alert_from_email_addrs''."}]}'''
  return_status: false
```
